##本地环境
server:
  port: 80
  context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 500
    accesslog:
      enabled: true
      directory: F://xjpapp/logs

xjpapp:
  mybatis:
    url: jdbc:mysql://127.0.0.1:3306/test_demo
    userName: root
    password: 123456
    driverClass: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 3000
    max-idle: 16
  global:
    db-type: mysql
    crypt-key: 2017/10/10xianjingdaijiayou!!!


logging:
  config: classpath:config/logback-dev.xml
  level: info
