##生产环境
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
    max-threads: 500
    accesslog:
      enabled: true
      directory: F://xjpapp/logs

  context-path: /

xjpapp:
  mybatis:
    url: jdbc:mysql://127.0.0.1:3306/test_demo
    userName: root
    password: 123456
    driverClass: com.mysql.jdbc.Driver

spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 3000
    password:
    pool:
      max-active: 16
      max-wait: -1
      max-idle: 16
      min-idle: 8

logging:
  config: classpath:config/logback-prd.xml
  level: info