##本地环境
server:
  port: 80
  context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 500
    accesslog:
      enabled: true
      directory: F://xjpapp/logs

xjpapp:
  mybatis:
    url: jdbc:mysql://127.0.0.1:3306/test_demo
    userName: root
    password: 123456
    driverClass: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 3000
    max-idle: 16
  global:
    db-type: mysql
    crypt-key: 2017/10/10xianjingdaijiayou!!!


logging:
  config: classpath:config/logback-dev.xml
  level: info

security:
  user:
    name: maopanpan
    password: 123456
  basic:
    enabled: true
    path: /system
management:
  port: 54001
  context-path: /system
  security:
    enabled: true
    roles: SUPERUSER


info:
  app:
    name: "com.demo"
    description: "#########"
    version: "1.0"
    spring-boot-version: "1.5.1"

endpoints:
  health:
    sensitive: false
    enabled: true
  mappings:
    sensitive: false
    enabled: true
  autoconfig:
    sensitive: true
    enabled: true
  configprops:
    sensitive: true
    enabled: true
  metrics:
    sensitive: true
    enabled: true